services:
  - type: web
    name: journal-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: journal-db
          property: connectionString

databases:
  - name: journal-db
    plan: free
